---
#name: dev
#
#on:
#
#  pull_request:
#    branches:
#      - "main"
#
#  push:
#    branches:
#      - "testing"
#
#  workflow_dispatch:
#    inputs:
#      logLevel:
#        description: "Log level"
#        required: true
#        default: "warning"
#
#jobs:
#
#  ci:
#    name: ci
#    runs-on: ubuntu-latest
#    env:
#      using_act: ${{ github.actor == 'nektos/act'}}
#      is_cron: ${{ github.event_name == 'schedule' }}
#
#    steps:
#
#      - name: Checkout.
#        uses: actions/checkout@v2
#
#      - uses: actions/setup-python@v2
#        with:
#          python-version: '3.7.x'
#
#      - uses: actions/setup-python@v2
#        with:
#          python-version: '3.8.x'
#
#      - uses: actions/setup-python@v2
#        with:
#          python-version: '3.9.x'
#
#      - name: Make sure path are there also for act shells.
#        if: env.using_act == 'true'
#        run: |
#          echo "export PATH=\"/opt/hostedtoolcache/Python/${{ env.python_version }}/x64:/opt/hostedtoolcache/Python/${{ env.python_version }}/x64/bin:$PATH\"" >> /root/.bashrc
#      - name: Upgrade pip.
#        run: python -m pip install --upgrade pip
#
#      - name: Install poetry and invoke.
#        run: pip install poetry invoke
#
#      - name: Configure poetry
#        run: poetry config virtualenvs.in-project true
#
#      - name: Install dependencies and test for all supported python version
#        run: inv test-all-python-version